apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stuartwdouglas/devfile-sample-go-basic?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
    pipelinesascode.tekton.dev/pipeline: "[.tekton/image-pipeline.yaml]"
    build.appstudio.redhat.com/produces: amd64
  labels:
    appstudio.openshift.io/application: devfile-sample-go-basic
    appstudio.openshift.io/component: devfile-sample-go-basic
    pipelines.appstudio.openshift.io/type: build
  name: devfile-sample-go-basic-on-pull-request-amd64
  namespace: sdouglas1-tenant
spec:
  params:
  - name: dockerfile
    value: docker/Dockerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/sdouglas1-tenant/devfile-sample-go-basic/devfile-sample-go-basic:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: image-build
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: { }
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
